name: dockerhub

on:
  push:
    tags:
      - "*"

jobs:
  build-library-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Get the tag name
      run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

    - name: Build and push (SITS CWL)
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: m3nin0/sitscwl:${{ env.TAG }}
        file: docker/library/Dockerfile

  build-environment-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get the tag name
      run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

    - name: Build and push (SITS CWL Execution environment)
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: m3nin0/sits:${{ env.TAG }}
        file: docker/execution/Dockerfile
