name: dockerhub

on:
  push:
    tags:
      - "*"

jobs:
  build-library-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Branch name
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF/refs\/tags\//}

    - name: Build and push (SITS CWL)
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: m3nin0/sitscwl:$SOURCE_TAG
        file: docker/library/Dockerfile
      env:
        SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}

  build-environment-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Branch name
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF/refs\/tags\//}

    - name: Build and push (SITS CWL)
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: m3nin0/sits:$SOURCE_TAG
        file: docker/execution/Dockerfile
      env:
        SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
